name: words
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - server
      - client

  client:
    image: "node:22"
    working_dir: /home/node
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client/:/home/node
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"

  server:
    image: todo-app/server
    build: ./server
    working_dir: /usr/src/app/server/src
    volumes:
      - ./server/src/:/usr/src/app/server/src
    expose:
      - "3001"
    ports:
      - 3001:3001
    command: uvicorn main:app --host 0.0.0.0 --port 3001 --reload
