name: words
services:
  nginx:
    image: nginx:1.17
    restart: on-failure:5
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - server
      - client

  client:
    image: "node:22"
    restart: unless-stopped
    working_dir: /home/node
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client/:/home/node
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"

  server:
    image: python:3.12
    restart: unless-stopped
    build: ./server
    working_dir: /server/
    volumes:
      - ./server:/server/
    expose:
      - "4000"
    ports:
      - 4000:4000
    command: python main.py --reload
