name: words
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - server
      - client
  client:
    image: "node:22"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client/:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
  server:
    image: todo-app/server
    build: ./server
    volumes:
      - ./server/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "3001:3001"
    command: "python src/server.py"
