name: words
services:

  # openru-db:
  #   image: postgres:17.0-bookworm
  #   restart: "no"
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./db/scripts:/docker-entrypoint-initdb.d


  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080


  nginx:
    image: nginx:1.17
    restart: on-failure:5
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - fastapi
      - nextjs

  nextjs:
    image: "node:22"
    restart: unless-stopped
    working_dir: /home/node
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client/:/home/node
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"

  fastapi:
    image: python:3.12
    restart: unless-stopped
    build: ./server/
    working_dir: /server/
    volumes:
      - ./server:/server/
    expose:
      - "4000"
    ports:
      - 4000:4000
    command: python main.py --reload
