"""first init

Revision ID: 65b0249048cc
Revises: 
Create Date: 2024-10-06 21:51:20.196301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65b0249048cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_accent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('word_class', sa.Enum('adjective', 'adverb', 'compound', 'conjunction', 'interjection', 'numeral', 'particle', 'phrase', 'preposition', 'pronoun', 'substantive', 'verb', name='wordclass'), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
